export const styles = {
    container: "bg-white",
    mainWrapper: "flex flex-col items-center px-50",
    headerContainer: "text-center py-20",
    largeTitle: "text-black text-8xl font-bold custom-font",
    subHeader: "text-black text-xl font-light",
    heroImage: "w-[50%] h-auto mx-auto py-3",
    dateText: "text-black text-sm font-light",
    sectionTitle: "text-3xl custom-font text-[#000000] mb-4",
    sectionText: "text-gray-700 text-xl font-light leading-relaxed text-justify",
    flexEnd: "flex justify-end",
    smallText: "text-sm",
    sectionSpacing: "py-12 pt-10 z-10",
    twoColumnGrid: "grid grid-cols-2 space-x-8",
    relativeContainer: "relative",
    imageFull: "relative w-full h-auto z-10",
    gridTwoColumnsCentered: "grid grid-cols-2 items-center relative z-10 space-x-8",
    imageConstrained: "w-full max-w-[400px] h-auto",
    sectionSpacingSmall: "py-1 pt-20 relative",
    flexColumn: "flex flex-col",
    sectionTextWithPadding: "text-gray-700 text-xl font-light leading-relaxed text-justify pt-16",
    sectionRelativePadding: "relative pt-10",
    imageFullRelative: "w-full h-auto relative",
    imageConstrainedRelative: "w-full max-w-[400px] h-auto relative",
    backButton: "fixed bottom-4 left-4 px-6 py-3 custom-button",
    upButton: "fixed bottom-4 right-4 px-10 py-3 custom-button",
    italic: "italic",
    fontBold: "font-bold",
    justifyCenter: "flex justify-center"
  };
