export const styles = {
  container: "bg-white",
  mainWrapper: "flex flex-col items-center px-50",
  headerContainer: "text-center py-20",
  largeTitle: "text-black text-8xl font-bold custom-font",
  subHeader: "text-black text-xl font-light",
  heroImage: "w-[70%] h-auto mx-auto py-3",
  dateText: "text-black text-sm font-light",
  sectionText: "text-gray-700 text-xl font-light leading-relaxed text-justify",
  italic: "italic",
  fontBold: "font-bold",
  sectionSpacing: "py-12 pt-10 z-10",
  twoColumnGrid: "grid grid-cols-2 space-x-8",
  relative: "relative",
  gridTwoColumnsCentered: "grid grid-cols-2 items-center relative z-10 space-x-8",
  imageFull: "relative w-full h-auto z-10",
  imageConstrained: "w-full max-w-[400px] h-auto",
  imageConstrainedRelative: "w-full max-w-[400px] h-auto relative",
  sectionRelativePadding: "relative pt-10",
  sectionSpacingRelative: "py-12 pt-10 relative",
  flexCenter: "flex justify-center",
  imageFullRelative: "w-full h-auto relative",
  imageFullMax: "w-full max-w-full h-auto relative",
  list: "list-disc ml-5",
  sectionTitle: "text-3xl custom-font text-[#000000] mb-4",
  backButton: "fixed bottom-4 left-4 px-6 py-3 custom-button",
  upButton: "fixed bottom-4 right-4 px-10 py-3 custom-button"
};
